// <auto-generated />
namespace YGN.DataAccesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class mig_stock_transaction_entity_has_been_changed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_stock_transaction_entity_has_been_changed));
        
        string IMigrationMetadata.Id
        {
            get { return "202312301053382_mig_stock_transaction_entity_has_been_changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
