// <auto-generated />
namespace YGN.DataAccesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class in_user_entity_date_format_has_been_changed2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(in_user_entity_date_format_has_been_changed2));
        
        string IMigrationMetadata.Id
        {
            get { return "202312291714056_in_user_entity_date_format_has_been_changed2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
