// <auto-generated />
namespace YGN.DataAccesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class mig_ClientCode_column_added_to_client_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_ClientCode_column_added_to_client_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202401211926385_mig_ClientCode_column_added_to_client_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
