// <auto-generated />
namespace YGN.DataAccesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class mig_in_Items_entity_category_field_has_been_regulated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_in_Items_entity_category_field_has_been_regulated));
        
        string IMigrationMetadata.Id
        {
            get { return "202401132100595_mig_in_Items_entity_category_field_has_been_regulated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
