// <auto-generated />
namespace YGN.DataAccesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class clien_entity_has_been_updated_using_fluent_validation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(clien_entity_has_been_updated_using_fluent_validation));
        
        string IMigrationMetadata.Id
        {
            get { return "202401141958489_clien_entity_has_been_updated_using_fluent_validation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
