// <auto-generated />
namespace YGN.DataAccesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class mig_item_entity_hasbeen_updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_item_entity_hasbeen_updated));
        
        string IMigrationMetadata.Id
        {
            get { return "202401261655322_mig_item_entity_hasbeen_updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
