// <auto-generated />
namespace YGN.DataAccesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class client_entity_has_been_created : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(client_entity_has_been_created));
        
        string IMigrationMetadata.Id
        {
            get { return "202401141952485_client_entity_has_been_created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
