// <auto-generated />
namespace YGN.DataAccesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class mig_orderline_entity_has_been_updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_orderline_entity_has_been_updated));
        
        string IMigrationMetadata.Id
        {
            get { return "202402020949103_mig_orderline_entity_has_been_updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
