// <auto-generated />
namespace YGN.DataAccesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class mig_city_chngs3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_city_chngs3));
        
        string IMigrationMetadata.Id
        {
            get { return "202401021019274_mig_city_chngs3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
