// <auto-generated />
namespace YGN.DataAccesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class mig_deleted_item_in_orderfiche_entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_deleted_item_in_orderfiche_entity));
        
        string IMigrationMetadata.Id
        {
            get { return "202402020829596_mig_deleted_item_in_orderfiche_entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
