//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTIONS
    {
        public int ID { get; set; }
        public Nullable<byte> TRCODE { get; set; }
        public Nullable<System.DateTime> PROCESSDATE { get; set; }
        public Nullable<int> ITEMID { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> AMOUNT { get; set; }
    
        public virtual ITEMS ITEMS { get; set; }
    }
}
